### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Daybreak-Zheng** [Johnathan-Xie/ZSD-YOLO#2]
You're doing a great job
What do the last 512 numbers in the Lable pt file mean？

**Comment by Johnathan-Xie** [comment]
These last 512 values are the image embeddings generated via the CLIP ViT-B/32 sized model. These are computed "offline" prior to the training process to optimize the data pipeline so that the embedding vectors do not need to be generated for every single training step.

Note that the text embedding vectors are generated during each training step as each class contains only a single embedding vector (so 80 vectors in total for COCO, and only 65 are used during the training process as seen classes) and these embedding vectors are simply selected based on the class label.
